// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzThqPEv_dpYsFtgNqgsiclH53o7wY02w',
    appId: '1:330657599280:web:8ba8a9f3976bcfcc78c2f5',
    messagingSenderId: '330657599280',
    projectId: 'healthtrack-4d60b',
    authDomain: 'healthtrack-4d60b.firebaseapp.com',
    storageBucket: 'healthtrack-4d60b.firebasestorage.app',
    measurementId: 'G-9SG64BQ90J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtnTniCrp-WQ72_9XMOGh6dwliZbHIoHg',
    appId: '1:330657599280:android:feb4a8418c99c5df78c2f5',
    messagingSenderId: '330657599280',
    projectId: 'healthtrack-4d60b',
    storageBucket: 'healthtrack-4d60b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoJFBLnidxl_Gaq4ke7wfx3lD_-QxCwxo',
    appId: '1:330657599280:ios:b1e0344dccd8f19b78c2f5',
    messagingSenderId: '330657599280',
    projectId: 'healthtrack-4d60b',
    storageBucket: 'healthtrack-4d60b.firebasestorage.app',
    iosBundleId: 'com.example.healthtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoJFBLnidxl_Gaq4ke7wfx3lD_-QxCwxo',
    appId: '1:330657599280:ios:b1e0344dccd8f19b78c2f5',
    messagingSenderId: '330657599280',
    projectId: 'healthtrack-4d60b',
    storageBucket: 'healthtrack-4d60b.firebasestorage.app',
    iosBundleId: 'com.example.healthtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzThqPEv_dpYsFtgNqgsiclH53o7wY02w',
    appId: '1:330657599280:web:8e4317d03687a3d878c2f5',
    messagingSenderId: '330657599280',
    projectId: 'healthtrack-4d60b',
    authDomain: 'healthtrack-4d60b.firebaseapp.com',
    storageBucket: 'healthtrack-4d60b.firebasestorage.app',
    measurementId: 'G-BELDD2CPEK',
  );
}
